// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgd8n708vacYWP-dx4VjkGDLCX-MS8_Fo',
    appId: '1:302361832417:web:efc49975d128949e7380a0',
    messagingSenderId: '302361832417',
    projectId: 'aviren-ff51f',
    authDomain: 'aviren-ff51f.firebaseapp.com',
    storageBucket: 'aviren-ff51f.appspot.com',
    measurementId: 'G-94JRK3QCYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC80GC3jdeH7ppxvUvVUrvEFwCchCV1Hc0',
    appId: '1:302361832417:android:71c4c3deed3178547380a0',
    messagingSenderId: '302361832417',
    projectId: 'aviren-ff51f',
    storageBucket: 'aviren-ff51f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDtorbsZxOjLJjFaqudmgkb-EVVPFWMc',
    appId: '1:302361832417:ios:5d0a02628cc401437380a0',
    messagingSenderId: '302361832417',
    projectId: 'aviren-ff51f',
    storageBucket: 'aviren-ff51f.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoDtorbsZxOjLJjFaqudmgkb-EVVPFWMc',
    appId: '1:302361832417:ios:288ff02e61971ec57380a0',
    messagingSenderId: '302361832417',
    projectId: 'aviren-ff51f',
    storageBucket: 'aviren-ff51f.appspot.com',
    iosBundleId: 'com.example.flutter1.RunnerTests',
  );
}
